stages:
  - build
  - release

image: node:15-buster

build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
release:
  stage: release
  dependencies:
    - build
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - ls -la
    - semantic-release --dry-run
